### ISSUE TITLE
Directory /tmp/jeedom/cache is not writeable

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost-Apps/jeedom_ynh#9]
Install succeed but when I try to login an alert box say "The directory /tmp/jeedom/cache is not writeable".

Any link with #3 ?

**Comment by thehotstyle** [comment]
sudo chmod -R 777 /tmp/jeedom/cache

**Comment by Aeris1One** [comment]
That's what I did and I reported the issue here because it shouldn't happen. Hope it will fixed soon
